version: "3.9"

services:
  central_postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app_postgres
    ports:
      - "5433:5432"

  shard0:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app_shard_0
    ports:
      - "5434:5432"

  shard1:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app_shard_1
    ports:
      - "5435:5432"

  shard2:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app_shard_2
    ports:
      - "5436:5432"
